const assert = require('node:assert/strict');
const fs = require('node:fs');
const puppeteer = require('puppeteer');
const base = process.argv[2] || 'http://127.0.0.1:8765';
(async () => {
  const executablePath = process.env.PUPPETEER_EXECUTABLE_PATH || ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium'].find(p => fs.existsSync(p));
  const browser = await puppeteer.launch({ headless: true, executablePath, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.setViewport({width:1440,height:1000});
    await page.goto(`${base}/vektor-viktor.html`);
    assert.equal(await page.$eval('.version-badge', e => e.textContent), 'v1.92');
    const result = await page.evaluate(async () => {
      const check = (ok, message) => { if (!ok) throw new Error(message); };
      const tick = () => new Promise(r => setTimeout(r, 30));
      const shape = (tag, attrs, mode='cut') => {
        const el = document.createElementNS(SVG_NS,tag);
        Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k,v));
        applyMode(el,mode);
        return addObject(tag,el,{mode});
      };
      const id=shape('rect',{x:10,y:10,width:60,height:50,rx:5,ry:5},'engrave');
      await tick(); check(projectDirty,'Drawing should be dirty');
      setProjectClean(true); selectOnly(id); zoomBy(1.25); await tick();
      check(!projectDirty,'Selection/zoom must not mark saved drawing dirty');
      check(fcmShapeSubpaths(objects[0].el)[0].segments.some(s=>s.type==='C'),'Rounded FCM corners');
      const before=serializeEditableProject();
      let failed=false;
      try { loadEditableProject({...before,objects:[...before.objects,{html:'<path'}]}); } catch { failed=true; }
      check(failed && objects.length===1 && objects[0].id===id,'Invalid project must preserve drawing');
      setPageSize('ScanNCut'); selectOnly(id); applySelectedScanFill('#123456');
      setProjectClean(true); currentScanFillColor='#abcdef'; selectOnly(id); await tick();
      check(objects[0].data.scanFillColor==='#123456','Selecting must preserve foil color');
      check(!projectDirty,'Selecting ScanNCut object must not mark dirty');
      const scanProject=serializeEditableProject(); loadEditableProject(scanProject); await tick();
      check(objects[0].data.scanFillColor==='#123456' && !projectDirty,'ScanNCut project roundtrip');
      const clone=prepareSvgExport(); forceFcmExportToRedLines(clone);
      const paths=fcmCollectPaths(clone).paths;
      check(paths.length>0 && fcmBuildFile(fcmSplitPathsIntoPieces(paths)).length>0,'FCM generation');
      setPageSize('A4');
      check(objects[0].data.mode==='engrave' && objects[0].el.getAttribute('fill')==='#000000','Restore laser mode');
      clearAll();
      const text=document.createElementNS(SVG_NS,'text');
      text.setAttribute('x','30'); text.setAttribute('y','50'); text.setAttribute('font-size','12'); text.setAttribute('font-family','Arial');
      text.setAttribute('data-vv-text','Hej med dig'); text.setAttribute('data-vv-curve-percent','30');
      text.textContent='Hej med dig'; applyMode(text,'cut');
      addObject('text',text,{mode:'cut',text:'Hej med dig'}); rebuildCurvedText(objects[0]);
      const img=document.createElementNS(SVG_NS,'image');
      img.setAttributeNS('http://www.w3.org/1999/xlink','xlink:href','data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==');
      img.setAttribute('width',10); img.setAttribute('height',10); addObject('image',img,{});
      const outline=textOutlinePath(objects[0].el);
      check(outline && outline.getAttribute('data-vv-fcm-keep-together')==='1','Text outline stays grouped');
      const textRoot=document.createElementNS(SVG_NS,'svg'); textRoot.appendChild(outline);
      check(fcmSplitPathsIntoPieces(fcmCollectPaths(textRoot).paths).length===1,'FCM keeps a whole text field together');
      const saved=serializeEditableProject(); check(saved.appVersion==='1.92','Project version');
      loadEditableProject(saved); await tick();
      check(objects.length===2 && textRawContent(objects[0])==='Hej med dig','Curved text/image roundtrip');
      setProjectClean(true); zoomBy(1.25); await tick();
      check(!projectDirty,'Text zoom must not mark saved drawing dirty');
      objects[0].el.setAttribute('x','40'); await tick();
      check(projectDirty,'Geometry change must mark dirty');
      projectDirtySince=Date.now()-PROJECT_SAVE_REMINDER_MS-1; checkProjectSaveReminder();
      check(document.querySelector('#saveReminderToast.show'),'Save reminder');
      hideSaveReminder(); check(getComputedStyle(document.getElementById('saveReminderToast')).visibility==='hidden','Dismissed reminder hidden from keyboard');
      setPageSize('ScanNCut'); selectOnly(objects[1].id); applySelectedScanFill('#345678');
      check(objects[1].el.getAttribute('filter').includes('#vvScanTint_'),'Image foil preview');
      setPageSize('A4');
      check(!objects[1].el.hasAttribute('filter') && !objects[1].el.style.filter,'Laser image must not retain foil tint');
      clearAll();
      const outer=shape('rect',{x:10,y:10,width:60,height:50},'engrave');
      const inner=shape('ellipse',{cx:40,cy:35,rx:10,ry:10},'cut');
      selectedIds=[outer,inner]; refreshUI(); document.getElementById('btnSubtract').click();
      await new Promise(r=>setTimeout(r,1000));
      check(objects.length===1,'Difference must create one compound object');
      const path=objects[0].el;
      check(path.getAttribute('fill')==='#000000','Difference retains base fill');
      check((path.getAttribute('d').match(/M/g)||[]).length>=2,'Difference retains inner contour');
      check(!path.isPointInFill(new DOMPoint(40,35)) && path.isPointInFill(new DOMPoint(15,15)),'Difference hole geometry');
      // Switch an A4 boolean result through the actual page/color controls.
      const differenceId=objects[0].id;
      const pageControl=document.getElementById('pageSize');
      pageControl.value='ScanNCut';pageControl.dispatchEvent(new Event('change',{bubbles:true}));
      check(selectedIds.includes(differenceId),'Page switch retains selection');
      check(!document.getElementById('scanColorPanel').classList.contains('hidden'),'ScanNCut color controls visible');
      const picker=document.getElementById('scanFillColor');
      const undoBeforeColor=undoStack.length;
      picker.value='#123456';picker.dispatchEvent(new Event('input',{bubbles:true}));
      check(objects[0].el.getAttribute('fill')==='#123456','A4 difference gets live ScanNCut fill');
      picker.value='#345678';picker.dispatchEvent(new Event('input',{bubbles:true}));
      picker.dispatchEvent(new Event('change',{bubbles:true}));
      check(undoStack.length===undoBeforeColor+1,'One undo for a color-picker gesture');
      check(!objects[0].el.isPointInFill(new DOMPoint(40,35)),'Color preserves difference hole');
      document.getElementById('btnClearScanFill').click();
      document.getElementById('btnApplyScanFill').click();
      check(objects[0].el.getAttribute('fill')==='#345678','Apply already-selected swatch after clearing');
      pageControl.value='A4';pageControl.dispatchEvent(new Event('change',{bubbles:true}));
      check(objects[0].el.getAttribute('fill')==='#000000','Switch back retains laser fill');
      pageControl.value='ScanNCut';pageControl.dispatchEvent(new Event('change',{bubbles:true}));
      check(objects[0].el.getAttribute('fill')==='#345678','Switch back retains foil fill');
      // ScanNCut preview color belongs to the material, not the cutter or active swatch.
      for (const baseColor of ['#123456', null]) {
        clearAll(); setPageSize('ScanNCut');
        const bottom=shape('rect',{x:10,y:10,width:60,height:50});
        applySelectedScanFill(baseColor);
        const top=shape('rect',{x:25,y:25,width:20,height:20});
        applySelectedScanFill('#abcdef'); currentScanFillColor='#ff0000';
        selectedIds=[top,bottom]; refreshUI(); document.getElementById('btnSubtract').click();
        await tick();
        check(objects.length===1,'ScanNCut difference creates one object');
        const difference=objects[0];
        check((difference.data.scanFillColor||null)===baseColor,'ScanNCut difference retains bottom foil color');
        check(difference.el.getAttribute('fill')===(baseColor||'none'),'ScanNCut difference displays bottom foil color');
        check(!difference.el.isPointInFill(new DOMPoint(35,35)),'ScanNCut difference retains hole');
        const project=serializeEditableProject();
        undo();
        check(objects.length===2 && (objects[0].data.scanFillColor||null)===baseColor,'Undo restores original colors');
        loadEditableProject(project); await tick();
        check(objects[0].el.getAttribute('fill')===(baseColor||'none'),'Difference color survives project roundtrip');
        const exported=prepareSvgExport(); forceFcmExportToRedLines(exported);
        check(exported.querySelector('[data-id]').getAttribute('fill')==='none','FCM remains unfilled cutting lines');
      }
      return 'Project roundtrip, invalid-file preservation, saved state, foil color, FCM, rounded corners, difference holes and ScanNCut difference colors';
    });
    assert.deepEqual(errors, []);
    await page.screenshot({path:'/tmp/vektor-viktor-review.png'});
    console.log(`PASS ${result}`);
  } finally { await browser.close(); }
})().catch(e=>{ console.error(e); process.exit(1); });
